export const mockMigrants: Migrant[] = [
  {
    id: 1,
    name: "Kim Minjun",
    nationality: "Korean",
    ethnicity: "Korean",
    latitude: 37.5665,
    longitude: 126.978,
    migrationYear: 2015,
    age: 35,
    occupation: "Software Engineer",
    education: "Bachelor's in Computer Science",
    languagesSpoken: ["Korean", "English"],
    connections: [
      { targetId: 2, targetType: "migrant", strength: 4, type: "friend" },
      { targetId: 3, targetType: "migrant", strength: 2, type: "friend" },
      { targetId: 4, targetType: "migrant", strength: 2, type: "friend" },
      {
        targetId: 1,
        targetType: "organization",
        strength: 3,
        type: "professional",
      },
    ],
    registrantId: "1", // Randomly assigned
  },
  {
    id: 2,
    name: "Liu Wei",
    nationality: "Chinese",
    ethnicity: "Han Chinese",
    latitude: 31.2304,
    longitude: 121.4737,
    migrationYear: 2010,
    age: 40,
    occupation: "Business Analyst",
    education: "Master's in Finance",
    languagesSpoken: ["Mandarin", "English"],
    connections: [
      { targetId: 3, targetType: "migrant", strength: 2, type: "colleague" },
      {
        targetId: 1,
        targetType: "organization",
        strength: 3,
        type: "business",
      },
    ],
    registrantId: "5", // Randomly assigned
  },
  {
    id: 3,
    name: "John Smith",
    nationality: "American",
    ethnicity: "Caucasian",
    latitude: 40.7128,
    longitude: -74.006,
    migrationYear: 2008,
    age: 45,
    occupation: "Marketing Manager",
    education: "Bachelor's in Marketing",
    languagesSpoken: ["English", "Spanish"],
    connections: [
      { targetId: 4, targetType: "migrant", strength: 5, type: "friend" },
      {
        targetId: 2,
        targetType: "organization",
        strength: 2,
        type: "business",
      },
    ],
    registrantId: "1", // Randomly assigned
  },
  {
    id: 4,
    name: "Sophie Dupont",
    nationality: "French",
    ethnicity: "European",
    latitude: 48.8566,
    longitude: 2.3522,
    migrationYear: 2017,
    age: 29,
    occupation: "Fashion Designer",
    education: "Bachelor's in Fashion Design",
    languagesSpoken: ["French", "English"],
    connections: [
      { targetId: 5, targetType: "migrant", strength: 3, type: "colleague" },
      {
        targetId: 3,
        targetType: "organization",
        strength: 4,
        type: "cultural",
      },
    ],
    registrantId: "1", // Randomly assigned
  },
  {
    id: 5,
    name: "Ali Hassan",
    nationality: "Egyptian",
    ethnicity: "Arab",
    latitude: 30.0444,
    longitude: 31.2357,
    migrationYear: 2012,
    age: 32,
    occupation: "Civil Engineer",
    education: "Master's in Civil Engineering",
    languagesSpoken: ["Arabic", "English"],
    connections: [
      { targetId: 2, targetType: "migrant", strength: 4, type: "friend" },
      { targetId: 3, targetType: "migrant", strength: 2, type: "friend" },
      { targetId: 4, targetType: "migrant", strength: 2, type: "friend" },
      { targetId: 6, targetType: "migrant", strength: 4, type: "friend" },
      {
        targetId: 4,
        targetType: "organization",
        strength: 3,
        type: "professional",
      },
    ],
    registrantId: "13", // Randomly assigned
  },
  {
    id: 6,
    name: "Maria Fernandez",
    nationality: "Mexican",
    ethnicity: "Latino",
    latitude: 19.4326,
    longitude: -99.1332,
    migrationYear: 2018,
    age: 30,
    occupation: "Teacher",
    education: "Bachelor's in Education",
    languagesSpoken: ["Spanish", "English"],
    connections: [
      {
        targetId: 1,
        targetType: "organization",
        strength: 4,
        type: "professional",
      },
      { targetId: 7, targetType: "migrant", strength: 5, type: "friend" },
    ],
    registrantId: "17", // Randomly assigned
  },
  {
    id: 7,
    name: "Ahmed Al-Sayed",
    nationality: "Jordanian",
    ethnicity: "Arab",
    latitude: 31.9632,
    longitude: 35.9308,
    migrationYear: 2019,
    age: 29,
    occupation: "Doctor",
    education: "Bachelor's in Medicine",
    languagesSpoken: ["Arabic", "English"],
    connections: [
      {
        targetId: 2,
        targetType: "organization",
        strength: 3,
        type: "business",
      },
      { targetId: 6, targetType: "migrant", strength: 5, type: "friend" },
    ],
    registrantId: "1", // Randomly assigned
  },
  {
    id: 8,
    name: "Olga Ivanova",
    nationality: "Russian",
    ethnicity: "Slavic",
    latitude: 55.7558,
    longitude: 37.6173,
    migrationYear: 2012,
    age: 36,
    occupation: "Engineer",
    education: "Master's in Mechanical Engineering",
    languagesSpoken: ["Russian", "English"],
    connections: [
      { targetId: 2, targetType: "migrant", strength: 4, type: "friend" },
      { targetId: 3, targetType: "migrant", strength: 2, type: "friend" },
      { targetId: 4, targetType: "migrant", strength: 3, type: "colleague" },
      {
        targetId: 1,
        targetType: "organization",
        strength: 2,
        type: "cultural",
      },
    ],
    registrantId: "19", // Randomly assigned
  },
  {
    id: 9,
    name: "Linh Nguyen",
    nationality: "Vietnamese",
    ethnicity: "Vietnamese",
    latitude: 21.0285,
    longitude: 105.8542,
    migrationYear: 2016,
    age: 28,
    occupation: "Accountant",
    education: "Bachelor's in Accounting",
    languagesSpoken: ["Vietnamese", "English"],
    connections: [
      {
        targetId: 4,
        targetType: "organization",
        strength: 3,
        type: "business",
      },
      { targetId: 9, targetType: "migrant", strength: 4, type: "friend" },
    ],
    registrantId: "4", // Randomly assigned
  },
  {
    id: 10,
    name: "Rajesh Kumar",
    nationality: "Indian",
    ethnicity: "South Asian",
    latitude: 28.6139,
    longitude: 77.209,
    migrationYear: 2014,
    age: 34,
    occupation: "Data Scientist",
    education: "Master's in Data Science",
    languagesSpoken: ["Hindi", "English"],
    connections: [
      {
        targetId: 5,
        targetType: "organization",
        strength: 4,
        type: "professional",
      },
      { targetId: 2, targetType: "migrant", strength: 4, type: "friend" },
      { targetId: 3, targetType: "migrant", strength: 2, type: "friend" },
      { targetId: 4, targetType: "migrant", strength: 2, type: "friend" },
      { targetId: 10, targetType: "migrant", strength: 3, type: "colleague" },
    ],
    registrantId: "1", // Randomly assigned
  },
  {
    id: 11,
    name: "Aisha Mbeki",
    nationality: "South African",
    ethnicity: "African",
    latitude: -26.2041,
    longitude: 28.0473,
    migrationYear: 2011,
    age: 39,
    occupation: "Social Worker",
    education: "Bachelor's in Social Work",
    languagesSpoken: ["Zulu", "English"],
    connections: [
      { targetId: 3, targetType: "migrant", strength: 3, type: "colleague" },
      {
        targetId: 2,
        targetType: "organization",
        strength: 2,
        type: "non-profit",
      },
    ],
    registrantId: "6", // Randomly assigned
  },
  {
    id: 12,
    name: "Fatima Rahman",
    nationality: "Pakistani",
    ethnicity: "South Asian",
    latitude: 30.3753,
    longitude: 69.3451,
    migrationYear: 2010,
    age: 42,
    occupation: "Research Scientist",
    education: "PhD in Biology",
    languagesSpoken: ["Urdu", "English"],
    connections: [
      {
        targetId: 5,
        targetType: "organization",
        strength: 4,
        type: "academic",
      },
      { targetId: 3, targetType: "migrant", strength: 2, type: "friend" },
      { targetId: 6, targetType: "migrant", strength: 2, type: "friend" },
    ],
    registrantId: "15", // Randomly assigned
  },
  {
    id: 13,
    name: "Mia Chen",
    nationality: "Taiwanese",
    ethnicity: "Han Chinese",
    latitude: 25.033,
    longitude: 121.5654,
    migrationYear: 2019,
    age: 26,
    occupation: "Graphic Designer",
    education: "Bachelor's in Design",
    languagesSpoken: ["Mandarin", "English"],
    connections: [
      {
        targetId: 1,
        targetType: "organization",
        strength: 3,
        type: "cultural",
      },
      { targetId: 5, targetType: "migrant", strength: 4, type: "friend" },
    ],
    registrantId: "1", // Randomly assigned
  },
  {
    id: 14,
    name: "Yusuf Ozdemir",
    nationality: "Turkish",
    ethnicity: "Turkish",
    latitude: 39.9334,
    longitude: 32.8597,
    migrationYear: 2018,
    age: 27,
    occupation: "Journalist",
    education: "Bachelor's in Journalism",
    languagesSpoken: ["Turkish", "English"],
    connections: [
      {
        targetId: 2,
        targetType: "organization",
        strength: 3,
        type: "media",
      },
      { targetId: 4, targetType: "migrant", strength: 2, type: "friend" },
    ],
    registrantId: "1", // Randomly assigned
  },
  {
    id: 15,
    name: "Nia Kanyoro",
    nationality: "Kenyan",
    ethnicity: "African",
    latitude: -1.286389,
    longitude: 36.817223,
    migrationYear: 2021,
    age: 24,
    occupation: "Data Analyst",
    education: "Bachelor's in Statistics",
    languagesSpoken: ["Swahili", "English"],
    connections: [
      { targetId: 3, targetType: "migrant", strength: 4, type: "friend" },
      {
        targetId: 1,
        targetType: "organization",
        strength: 2,
        type: "non-profit",
      },
    ],
    registrantId: "9", // Randomly assigned
  },
  {
    id: 16,
    name: "Ravi Patel",
    nationality: "Indian",
    ethnicity: "South Asian",
    latitude: 20.5937,
    longitude: 78.9629,
    migrationYear: 2013,
    age: 36,
    occupation: "Software Developer",
    education: "Master's in Computer Science",
    languagesSpoken: ["Hindi", "English"],
    connections: [
      { targetId: 4, targetType: "migrant", strength: 3, type: "colleague" },
      { targetId: 5, targetType: "migrant", strength: 2, type: "friend" },
    ],
    registrantId: "1", // Randomly assigned
  },
  {
    id: 17,
    name: "Clara Schwartz",
    nationality: "German",
    ethnicity: "European",
    latitude: 52.52,
    longitude: 13.405,
    migrationYear: 2015,
    age: 38,
    occupation: "Project Manager",
    education: "Bachelor's in Business Administration",
    languagesSpoken: ["German", "English"],
    connections: [
      {
        targetId: 5,
        targetType: "organization",
        strength: 4,
        type: "corporate",
      },
      { targetId: 6, targetType: "migrant", strength: 3, type: "friend" },
    ],
    registrantId: "1", // Randomly assigned
  },
  {
    id: 18,
    name: "Yuki Tanaka",
    nationality: "Japanese",
    ethnicity: "Japanese",
    latitude: 35.682839,
    longitude: 139.759455,
    migrationYear: 2016,
    age: 33,
    occupation: "Web Developer",
    education: "Bachelor's in Information Technology",
    languagesSpoken: ["Japanese", "English"],
    connections: [
      {
        targetId: 1,
        targetType: "organization",
        strength: 4,
        type: "technology",
      },
      { targetId: 4, targetType: "migrant", strength: 5, type: "friend" },
    ],
    registrantId: "18", // Randomly assigned
  },
  {
    id: 19,
    name: "Ibrahim Kamara",
    nationality: "Sierra Leonean",
    ethnicity: "African",
    latitude: 8.486,
    longitude: -11.7799,
    migrationYear: 2020,
    age: 25,
    occupation: "Entrepreneur",
    education: "Bachelor's in Business",
    languagesSpoken: ["English", "Krio"],
    connections: [
      {
        targetId: 5,
        targetType: "organization",
        strength: 2,
        type: "non-profit",
      },
      { targetId: 6, targetType: "migrant", strength: 3, type: "friend" },
    ],
    registrantId: "7", // Randomly assigned
  },
  {
    id: 20,
    name: "Svetlana Petrov",
    nationality: "Ukrainian",
    ethnicity: "Slavic",
    latitude: 50.4501,
    longitude: 30.5234,
    migrationYear: 2019,
    age: 31,
    occupation: "Graphic Artist",
    education: "Bachelor's in Arts",
    languagesSpoken: ["Ukrainian", "English"],
    connections: [
      {
        targetId: 3,
        targetType: "organization",
        strength: 4,
        type: "cultural",
      },
      { targetId: 4, targetType: "migrant", strength: 3, type: "friend" },
    ],
    registrantId: "14", // Randomly assigned
  },
  {
    id: 31,
    name: "Han Soo-jin",
    nationality: "Russian",
    ethnicity: "Korean",
    latitude: 43.1025,
    longitude: 131.9129,
    migrationYear: 1908,
    age: 52,
    occupation: "Seamstress",
    education: "High School Diploma",
    languagesSpoken: ["Korean", "Russian"],
    connections: [
      { targetId: 29, targetType: "migrant", strength: 5, type: "family" },
      { targetId: 33, targetType: "migrant", strength: 3, type: "community" },
    ],
    registrantId: 1, // 등록자 1
  },
  {
    id: 32,
    name: "Kang Byung-ho",
    nationality: "Russian",
    ethnicity: "Korean",
    latitude: 42.7876,
    longitude: 131.897,
    migrationYear: 1913,
    age: 46,
    occupation: "Logger",
    education: "Primary Education",
    languagesSpoken: ["Korean", "Russian"],
    connections: [
      { targetId: 30, targetType: "migrant", strength: 3, type: "colleague" },
      { targetId: 34, targetType: "migrant", strength: 4, type: "friend" },
    ],
    registrantId: 2, // 등록자 2
  },
  {
    id: 33,
    name: "Kim Hae-won",
    nationality: "Russian",
    ethnicity: "Korean",
    latitude: 42.6547,
    longitude: 132.4453,
    migrationYear: 1906,
    age: 55,
    occupation: "Community Leader",
    education: "Bachelor's in Political Science",
    languagesSpoken: ["Korean", "Russian"],
    connections: [
      { targetId: 31, targetType: "migrant", strength: 3, type: "community" },
      { targetId: 35, targetType: "migrant", strength: 4, type: "leader" },
    ],
    registrantId: 3, // 등록자 3
  },
  {
    id: 34,
    name: "Nam Ji-woo",
    nationality: "Russian",
    ethnicity: "Korean",
    latitude: 42.897,
    longitude: 131.1234,
    migrationYear: 1910,
    age: 60,
    occupation: "Teacher",
    education: "Master's in Education",
    languagesSpoken: ["Korean", "Russian"],
    connections: [
      { targetId: 29, targetType: "migrant", strength: 2, type: "friend" },
      { targetId: 30, targetType: "migrant", strength: 4, type: "colleague" },
    ],
    registrantId: 4, // 등록자 4
  },
  {
    id: 35,
    name: "Park Min-seok",
    nationality: "Russian",
    ethnicity: "Korean",
    latitude: 43.456,
    longitude: 132.123,
    migrationYear: 1912,
    age: 48,
    occupation: "Farmer",
    education: "Middle School Diploma",
    languagesSpoken: ["Korean", "Russian"],
    connections: [
      { targetId: 32, targetType: "migrant", strength: 4, type: "family" },
      { targetId: 33, targetType: "migrant", strength: 5, type: "community" },
    ],
    registrantId: 1, // 등록자 1
  },
  {
    id: 36,
    name: "Lee Sang-woo",
    nationality: "Russian",
    ethnicity: "Korean",
    latitude: 43.123,
    longitude: 132.234,
    migrationYear: 1915,
    age: 40,
    occupation: "Blacksmith",
    education: "Vocational Training",
    languagesSpoken: ["Korean", "Russian"],
    connections: [
      { targetId: 34, targetType: "migrant", strength: 3, type: "colleague" },
      { targetId: 31, targetType: "migrant", strength: 4, type: "friend" },
    ],
    registrantId: 2, // 등록자 2
  },
  {
    id: 37,
    name: "Choi Eun-jung",
    nationality: "Russian",
    ethnicity: "Korean",
    latitude: 42.678,
    longitude: 131.456,
    migrationYear: 1909,
    age: 53,
    occupation: "Shopkeeper",
    education: "High School Diploma",
    languagesSpoken: ["Korean", "Russian"],
    connections: [
      { targetId: 32, targetType: "migrant", strength: 5, type: "family" },
      { targetId: 33, targetType: "migrant", strength: 3, type: "community" },
    ],
    registrantId: 3, // 등록자 3
  },
  {
    id: 38,
    name: "Yoon Ji-hoon",
    nationality: "Russian",
    ethnicity: "Korean",
    latitude: 43.345,
    longitude: 132.789,
    migrationYear: 1911,
    age: 45,
    occupation: "Tailor",
    education: "Middle School Diploma",
    languagesSpoken: ["Korean", "Russian"],
    connections: [
      { targetId: 35, targetType: "migrant", strength: 4, type: "friend" },
      { targetId: 34, targetType: "migrant", strength: 2, type: "colleague" },
    ],
    registrantId: 4, // 등록자 4
  },
  {
    id: 39,
    name: "Seo Jin-kyu",
    nationality: "Russian",
    ethnicity: "Korean",
    latitude: 42.456,
    longitude: 131.234,
    migrationYear: 1905,
    age: 57,
    occupation: "Medic",
    education: "Bachelor's in Medicine",
    languagesSpoken: ["Korean", "Russian"],
    connections: [
      { targetId: 36, targetType: "migrant", strength: 3, type: "community" },
      { targetId: 31, targetType: "migrant", strength: 5, type: "family" },
    ],
    registrantId: 1, // 등록자 1
  },
  {
    id: 40,
    name: "Lee Sun-young",
    nationality: "Russian",
    ethnicity: "Korean",
    latitude: 43.876,
    longitude: 132.456,
    migrationYear: 1916,
    age: 39,
    occupation: "Cobbler",
    education: "Primary Education",
    languagesSpoken: ["Korean", "Russian"],
    connections: [
      { targetId: 35, targetType: "migrant", strength: 4, type: "friend" },
      { targetId: 38, targetType: "migrant", strength: 3, type: "colleague" },
    ],
    registrantId: 2, // 등록자 2
  },
  {
    id: 41,
    name: "Kwon Soo-yeon",
    nationality: "Russian",
    ethnicity: "Korean",
    latitude: 42.987,
    longitude: 132.123,
    migrationYear: 1914,
    age: 42,
    occupation: "Baker",
    education: "High School Diploma",
    languagesSpoken: ["Korean", "Russian"],
    connections: [
      { targetId: 33, targetType: "migrant", strength: 5, type: "family" },
      { targetId: 37, targetType: "migrant", strength: 4, type: "community" },
    ],
    registrantId: 3, // 등록자 3
  },
  {
    id: 42,
    name: "Jang Hyun-woo",
    nationality: "Russian",
    ethnicity: "Korean",
    latitude: 42.765,
    longitude: 131.678,
    migrationYear: 1904,
    age: 60,
    occupation: "Merchant",
    education: "Bachelor's in Business",
    languagesSpoken: ["Korean", "Russian"],
    connections: [
      { targetId: 38, targetType: "migrant", strength: 3, type: "colleague" },
      { targetId: 36, targetType: "migrant", strength: 5, type: "friend" },
    ],
    registrantId: 4, // 등록자 4
  },
  {
    id: 43,
    name: "Kim Jae-hwan",
    nationality: "Russian",
    ethnicity: "Korean",
    latitude: 43.654,
    longitude: 132.345,
    migrationYear: 1913,
    age: 44,
    occupation: "Fisherman",
    education: "Primary Education",
    languagesSpoken: ["Korean", "Russian"],
    connections: [
      { targetId: 41, targetType: "migrant", strength: 4, type: "friend" },
      { targetId: 39, targetType: "migrant", strength: 3, type: "community" },
    ],
    registrantId: 1, // 등록자 1
  },
  {
    id: 44,
    name: "Hong Soo-min",
    nationality: "Russian",
    ethnicity: "Korean",
    latitude: 42.456,
    longitude: 132.654,
    migrationYear: 1908,
    age: 55,
    occupation: "Teacher",
    education: "Bachelor's in Education",
    languagesSpoken: ["Korean", "Russian"],
    connections: [
      { targetId: 42, targetType: "migrant", strength: 4, type: "colleague" },
      { targetId: 37, targetType: "migrant", strength: 5, type: "friend" },
    ],
    registrantId: 2, // 등록자 2
  },
  {
    id: 45,
    name: "Seo Young-ja",
    nationality: "Russian",
    ethnicity: "Korean",
    latitude: 42.789,
    longitude: 132.123,
    migrationYear: 1910,
    age: 50,
    occupation: "Seamstress",
    education: "High School Diploma",
    languagesSpoken: ["Korean", "Russian"],
    connections: [
      { targetId: 43, targetType: "migrant", strength: 3, type: "community" },
      { targetId: 40, targetType: "migrant", strength: 4, type: "friend" },
    ],
    registrantId: 3, // 등록자 3
  },
  {
    id: 46,
    name: "Kang Hyun-sook",
    nationality: "Russian",
    ethnicity: "Korean",
    latitude: 43.234,
    longitude: 132.987,
    migrationYear: 1911,
    age: 43,
    occupation: "Nurse",
    education: "Associate's in Nursing",
    languagesSpoken: ["Korean", "Russian"],
    connections: [
      { targetId: 44, targetType: "migrant", strength: 5, type: "family" },
      { targetId: 38, targetType: "migrant", strength: 3, type: "colleague" },
    ],
    registrantId: 4, // 등록자 4
  },
  {
    id: 47,
    name: "Joo Mi-sook",
    nationality: "Russian",
    ethnicity: "Korean",
    latitude: 43.567,
    longitude: 132.876,
    migrationYear: 1907,
    age: 56,
    occupation: "Herbalist",
    education: "Vocational Training",
    languagesSpoken: ["Korean", "Russian"],
    connections: [
      { targetId: 41, targetType: "migrant", strength: 4, type: "community" },
      { targetId: 45, targetType: "migrant", strength: 5, type: "friend" },
    ],
    registrantId: 1, // 등록자 1
  },
  {
    id: 48,
    name: "Lee Tae-ho",
    nationality: "Russian",
    ethnicity: "Korean",
    latitude: 42.345,
    longitude: 131.234,
    migrationYear: 1915,
    age: 41,
    occupation: "Mechanic",
    education: "High School Diploma",
    languagesSpoken: ["Korean", "Russian"],
    connections: [
      { targetId: 44, targetType: "migrant", strength: 3, type: "friend" },
      { targetId: 39, targetType: "migrant", strength: 4, type: "community" },
    ],
    registrantId: 2, // 등록자 2
  },
  {
    id: 49,
    name: "Yoon Seung-yeon",
    nationality: "Russian",
    ethnicity: "Korean",
    latitude: 42.123,
    longitude: 132.456,
    migrationYear: 1914,
    age: 38,
    occupation: "Artist",
    education: "Bachelor's in Fine Arts",
    languagesSpoken: ["Korean", "Russian"],
    connections: [
      { targetId: 46, targetType: "migrant", strength: 5, type: "friend" },
      { targetId: 47, targetType: "migrant", strength: 3, type: "colleague" },
    ],
    registrantId: 3, // 등록자 3
  },
  {
    id: 50,
    name: "Park Joon-ho",
    nationality: "Russian",
    ethnicity: "Korean",
    latitude: 43.678,
    longitude: 132.345,
    migrationYear: 1906,
    age: 58,
    occupation: "Veterinarian",
    education: "Doctorate in Veterinary Science",
    languagesSpoken: ["Korean", "Russian"],
    connections: [
      { targetId: 45, targetType: "migrant", strength: 4, type: "community" },
      { targetId: 40, targetType: "migrant", strength: 2, type: "friend" },
    ],
    registrantId: 4, // 등록자 4
  },
  {
    id: 51,
    name: "Yuri Petrov",
    nationality: "Russian",
    ethnicity: "Korean",
    latitude: 43.123,
    longitude: 131.567,
    migrationYear: 1910,
    age: 65,
    occupation: "Teacher",
    education: "Master's in Education",
    languagesSpoken: ["Korean", "Russian"],
    connections: [
      { targetId: 40, targetType: "migrant", strength: 5, type: "community" },
      { targetId: 44, targetType: "migrant", strength: 4, type: "friend" },
      { targetId: 37, targetType: "migrant", strength: 3, type: "mentor" },
      { targetId: 38, targetType: "migrant", strength: 3, type: "colleague" },
      { targetId: 39, targetType: "migrant", strength: 2, type: "network" },
    ],
    registrantId: 5,
  },
  {
    id: 52,
    name: "Minh Nguyen",
    nationality: "Vietnamese",
    ethnicity: "Korean",
    latitude: 10.7769,
    longitude: 106.6958,
    migrationYear: 1975,
    age: 49,
    occupation: "Business Owner",
    education: "Bachelor's in Business Administration",
    languagesSpoken: ["Korean", "Vietnamese", "English"],
    connections: [
      { targetId: 41, targetType: "migrant", strength: 5, type: "business" },
      { targetId: 45, targetType: "migrant", strength: 4, type: "partner" },
      {
        targetId: 38,
        targetType: "migrant",
        strength: 3,
        type: "collaborator",
      },
      { targetId: 37, targetType: "migrant", strength: 2, type: "friend" },
      { targetId: 36, targetType: "migrant", strength: 2, type: "network" },
    ],
    registrantId: 6,
  },
  {
    id: 53,
    name: "Sofia Rodriguez",
    nationality: "Spanish",
    ethnicity: "Korean",
    latitude: 40.4168,
    longitude: -3.7038,
    migrationYear: 2005,
    age: 39,
    occupation: "Artist",
    education: "Bachelor's in Fine Arts",
    languagesSpoken: ["Korean", "Spanish", "English"],
    connections: [
      { targetId: 44, targetType: "migrant", strength: 5, type: "art" },
      { targetId: 39, targetType: "migrant", strength: 4, type: "friend" },
      {
        targetId: 42,
        targetType: "migrant",
        strength: 3,
        type: "collaborator",
      },
      { targetId: 45, targetType: "migrant", strength: 2, type: "network" },
      { targetId: 40, targetType: "migrant", strength: 2, type: "mentor" },
    ],
    registrantId: 7,
  },
  {
    id: 54,
    name: "Amina Khakimova",
    nationality: "Kazakh",
    ethnicity: "Korean",
    latitude: 43.222,
    longitude: 76.8512,
    migrationYear: 1991,
    age: 33,
    occupation: "Engineer",
    education: "Master's in Engineering",
    languagesSpoken: ["Korean", "Kazakh", "Russian"],
    connections: [
      {
        targetId: 38,
        targetType: "migrant",
        strength: 5,
        type: "professional",
      },
      { targetId: 41, targetType: "migrant", strength: 4, type: "colleague" },
      { targetId: 39, targetType: "migrant", strength: 3, type: "friend" },
      { targetId: 45, targetType: "migrant", strength: 2, type: "network" },
      { targetId: 40, targetType: "migrant", strength: 2, type: "mentor" },
    ],
    registrantId: 8,
  },
  {
    id: 55,
    name: "Liu Wei",
    nationality: "Chinese",
    ethnicity: "Korean",
    latitude: 39.9042,
    longitude: 116.4074,
    migrationYear: 1980,
    age: 44,
    occupation: "Chef",
    education: "Diploma in Culinary Arts",
    languagesSpoken: ["Korean", "Mandarin"],
    connections: [
      { targetId: 42, targetType: "migrant", strength: 5, type: "business" },
      { targetId: 41, targetType: "migrant", strength: 4, type: "friend" },
      {
        targetId: 39,
        targetType: "migrant",
        strength: 3,
        type: "collaborator",
      },
      { targetId: 40, targetType: "migrant", strength: 2, type: "network" },
      { targetId: 38, targetType: "migrant", strength: 2, type: "mentor" },
    ],
    registrantId: 9,
  },
  {
    id: 56,
    name: "Fatima Al-Najjar",
    nationality: "Egyptian",
    ethnicity: "Korean",
    latitude: 30.0444,
    longitude: 31.2357,
    migrationYear: 2010,
    age: 34,
    occupation: "Journalist",
    education: "Bachelor's in Journalism",
    languagesSpoken: ["Korean", "Arabic", "English"],
    connections: [
      { targetId: 40, targetType: "migrant", strength: 5, type: "media" },
      { targetId: 43, targetType: "migrant", strength: 4, type: "friend" },
      {
        targetId: 39,
        targetType: "migrant",
        strength: 3,
        type: "collaborator",
      },
      { targetId: 41, targetType: "migrant", strength: 2, type: "network" },
      { targetId: 44, targetType: "migrant", strength: 2, type: "mentor" },
    ],
    registrantId: 10,
  },
  {
    id: 57,
    name: "Nadia Ahmed",
    nationality: "Pakistani",
    ethnicity: "Korean",
    latitude: 30.3753,
    longitude: 69.3451,
    migrationYear: 2008,
    age: 36,
    occupation: "Software Developer",
    education: "Bachelor's in Computer Science",
    languagesSpoken: ["Korean", "Urdu", "English"],
    connections: [
      {
        targetId: 42,
        targetType: "migrant",
        strength: 5,
        type: "professional",
      },
      { targetId: 43, targetType: "migrant", strength: 4, type: "friend" },
      {
        targetId: 40,
        targetType: "migrant",
        strength: 3,
        type: "collaborator",
      },
      { targetId: 39, targetType: "migrant", strength: 2, type: "network" },
      { targetId: 44, targetType: "migrant", strength: 2, type: "mentor" },
    ],
    registrantId: 11,
  },
  {
    id: 58,
    name: "Anjali Sharma",
    nationality: "Indian",
    ethnicity: "Korean",
    latitude: 20.5937,
    longitude: 78.9629,
    migrationYear: 2006,
    age: 38,
    occupation: "Nurse",
    education: "Bachelor's in Nursing",
    languagesSpoken: ["Korean", "Hindi", "English"],
    connections: [
      {
        targetId: 45,
        targetType: "migrant",
        strength: 5,
        type: "healthcare",
      },
      { targetId: 39, targetType: "migrant", strength: 4, type: "friend" },
      {
        targetId: 44,
        targetType: "migrant",
        strength: 3,
        type: "collaborator",
      },
      { targetId: 42, targetType: "migrant", strength: 2, type: "network" },
      { targetId: 40, targetType: "migrant", strength: 2, type: "mentor" },
    ],
    registrantId: 12,
  },
  {
    id: 59,
    name: "Laila Hassan",
    nationality: "Jordanian",
    ethnicity: "Korean",
    latitude: 30.5852,
    longitude: 36.2384,
    migrationYear: 2011,
    age: 33,
    occupation: "Architect",
    education: "Master's in Architecture",
    languagesSpoken: ["Korean", "Arabic", "English"],
    connections: [
      { targetId: 40, targetType: "migrant", strength: 5, type: "design" },
      {
        targetId: 42,
        targetType: "migrant",
        strength: 4,
        type: "collaborator",
      },
      { targetId: 41, targetType: "migrant", strength: 3, type: "friend" },
      { targetId: 39, targetType: "migrant", strength: 2, type: "network" },
      { targetId: 43, targetType: "migrant", strength: 2, type: "mentor" },
    ],
    registrantId: 13,
  },
  {
    id: 60,
    name: "Isabella Costa",
    nationality: "Brazilian",
    ethnicity: "Korean",
    latitude: -23.5505,
    longitude: -46.6333,
    migrationYear: 2009,
    age: 35,
    occupation: "Pharmacist",
    education: "Doctorate in Pharmacy",
    languagesSpoken: ["Korean", "Portuguese", "English"],
    connections: [
      {
        targetId: 41,
        targetType: "migrant",
        strength: 5,
        type: "healthcare",
      },
      {
        targetId: 42,
        targetType: "migrant",
        strength: 4,
        type: "collaborator",
      },
      { targetId: 40, targetType: "migrant", strength: 3, type: "friend" },
      { targetId: 39, targetType: "migrant", strength: 2, type: "network" },
      { targetId: 43, targetType: "migrant", strength: 2, type: "mentor" },
    ],
    registrantId: 14,
  },
];

export const mockOrganizations: Organization[] = [
  {
    id: 1,
    name: "Korean Cultural Center - LA",
    latitude: 34.0622,
    longitude: -118.3026,
    foundationYear: 1980,
    type: "Cultural",
    mission: "Promote Korean culture and support Korean immigrants",
    services: ["Language classes", "Cultural events", "Immigration support"],
    contactInfo: "info@kccla.org",
    registrantId: 1,
    connections: [
      { targetId: 1, targetType: "migrant", strength: 3, type: "cultural" },
      {
        targetId: 2,
        targetType: "organization",
        strength: 4,
        type: "professional",
      },
    ],
  },
  {
    id: 2,
    name: "Asian Business Association",
    latitude: 34.0522,
    longitude: -118.2437,
    foundationYear: 1995,
    type: "Business",
    mission: "Support Asian business owners in LA",
    services: ["Business workshops", "Networking events"],
    contactInfo: "contact@abala.org",
    registrantId: 2,
    connections: [
      { targetId: 2, targetType: "migrant", strength: 2, type: "business" },
      {
        targetId: 1,
        targetType: "organization",
        strength: 4,
        type: "professional",
      },
    ],
  },
  {
    id: 3,
    name: "Korean American Coalition",
    latitude: 34.0632,
    longitude: -118.2986,
    foundationYear: 1999,
    type: "Advocacy",
    mission: "Advocate for Korean American rights and representation",
    services: ["Policy advocacy", "Community organizing"],
    contactInfo: "info@kac.org",
    registrantId: 3,
    connections: [
      { targetId: 1, targetType: "migrant", strength: 5, type: "advocacy" },
      {
        targetId: 2,
        targetType: "organization",
        strength: 3,
        type: "collaboration",
      },
    ],
  },
  {
    id: 4,
    name: "Korean Food Foundation",
    latitude: 34.0703,
    longitude: -118.2325,
    foundationYear: 2010,
    type: "Cultural",
    mission: "Promote Korean cuisine and culture",
    services: ["Cooking classes", "Food festivals"],
    contactInfo: "info@koreanfoodfoundation.org",
    registrantId: 4,
    connections: [
      { targetId: 1, targetType: "migrant", strength: 2, type: "cultural" },
      {
        targetId: 3,
        targetType: "organization",
        strength: 5,
        type: "collaboration",
      },
    ],
  },
  {
    id: 5,
    name: "Korean American Chamber of Commerce",
    latitude: 34.0485,
    longitude: -118.2584,
    foundationYear: 2005,
    type: "Business",
    mission: "Support Korean American businesses",
    services: ["Business networking", "Advocacy"],
    contactInfo: "info@kacc.org",
    registrantId: 5,
    connections: [
      { targetId: 2, targetType: "migrant", strength: 3, type: "business" },
      {
        targetId: 1,
        targetType: "organization",
        strength: 4,
        type: "collaboration",
      },
    ],
  },
  {
    id: 6,
    name: "Korean Historical Society",
    latitude: 34.0672,
    longitude: -118.258,
    foundationYear: 2000,
    type: "Cultural",
    mission: "Preserve and promote Korean history and heritage",
    services: ["Exhibitions", "Workshops"],
    contactInfo: "info@khs.org",
    registrantId: 6,
    connections: [
      { targetId: 3, targetType: "migrant", strength: 2, type: "cultural" },
      {
        targetId: 4,
        targetType: "organization",
        strength: 4,
        type: "collaboration",
      },
    ],
  },
  {
    id: 7,
    name: "Korean Art Institute",
    latitude: 34.0582,
    longitude: -118.3085,
    foundationYear: 2012,
    type: "Cultural",
    mission: "Promote Korean art and artists",
    services: ["Art exhibitions", "Artist residencies"],
    contactInfo: "contact@koreanart.org",
    registrantId: 7,
    connections: [
      { targetId: 1, targetType: "migrant", strength: 3, type: "cultural" },
      {
        targetId: 6,
        targetType: "organization",
        strength: 5,
        type: "collaboration",
      },
    ],
  },
  {
    id: 8,
    name: "Korean American Family Services",
    latitude: 34.0752,
    longitude: -118.2572,
    foundationYear: 1998,
    type: "Social Services",
    mission: "Support Korean American families",
    services: ["Counseling", "Family support"],
    contactInfo: "info@kafs.org",
    registrantId: 8,
    connections: [
      { targetId: 5, targetType: "migrant", strength: 3, type: "social" },
      {
        targetId: 2,
        targetType: "organization",
        strength: 4,
        type: "collaboration",
      },
    ],
  },
  {
    id: 9,
    name: "Korean Women's Association",
    latitude: 34.0706,
    longitude: -118.267,
    foundationYear: 2003,
    type: "Advocacy",
    mission: "Empower Korean women in the community",
    services: ["Workshops", "Advocacy programs"],
    contactInfo: "info@kwa.org",
    registrantId: 9,
    connections: [
      { targetId: 1, targetType: "migrant", strength: 4, type: "advocacy" },
      {
        targetId: 3,
        targetType: "organization",
        strength: 2,
        type: "collaboration",
      },
    ],
  },
  {
    id: 10,
    name: "Korean American Medical Society",
    latitude: 34.0479,
    longitude: -118.2528,
    foundationYear: 1996,
    type: "Health",
    mission: "Promote health and wellness in the Korean community",
    services: ["Health fairs", "Medical assistance"],
    contactInfo: "info@kams.org",
    registrantId: 10,
    connections: [
      { targetId: 4, targetType: "migrant", strength: 3, type: "health" },
      {
        targetId: 9,
        targetType: "organization",
        strength: 4,
        type: "collaboration",
      },
    ],
  },
  {
    id: 11,
    name: "Korean Youth Community Center",
    latitude: 34.0652,
    longitude: -118.2578,
    foundationYear: 2007,
    type: "Youth",
    mission: "Empower Korean youth through education and engagement",
    services: ["Tutoring", "Leadership programs"],
    contactInfo: "info@kycc.org",
    registrantId: 11,
    connections: [
      { targetId: 6, targetType: "migrant", strength: 4, type: "youth" },
      {
        targetId: 8,
        targetType: "organization",
        strength: 5,
        type: "collaboration",
      },
    ],
  },
  {
    id: 12,
    name: "Korean American Parent Association",
    latitude: 34.0728,
    longitude: -118.2494,
    foundationYear: 2015,
    type: "Advocacy",
    mission: "Support Korean American parents in education",
    services: ["Workshops", "Advocacy"],
    contactInfo: "info@kapa.org",
    registrantId: 12,
    connections: [
      { targetId: 5, targetType: "migrant", strength: 3, type: "advocacy" },
      {
        targetId: 11,
        targetType: "organization",
        strength: 4,
        type: "collaboration",
      },
    ],
  },
  {
    id: 13,
    name: "Korean Language School",
    latitude: 34.0666,
    longitude: -118.2586,
    foundationYear: 2001,
    type: "Educational",
    mission: "Teach the Korean language to the community",
    services: ["Korean language classes", "Cultural workshops"],
    contactInfo: "info@koreanschool.org",
    registrantId: 13,
    connections: [
      { targetId: 2, targetType: "migrant", strength: 5, type: "educational" },
      {
        targetId: 4,
        targetType: "organization",
        strength: 4,
        type: "collaboration",
      },
    ],
  },
  {
    id: 14,
    name: "Korean Art Society",
    latitude: 34.0596,
    longitude: -118.265,
    foundationYear: 2004,
    type: "Cultural",
    mission: "Promote Korean art and culture through exhibitions",
    services: ["Art exhibitions", "Community events"],
    contactInfo: "info@kas.org",
    registrantId: 14,
    connections: [
      { targetId: 1, targetType: "migrant", strength: 4, type: "cultural" },
      {
        targetId: 8,
        targetType: "organization",
        strength: 3,
        type: "collaboration",
      },
    ],
  },
  {
    id: 15,
    name: "Korean Business Association",
    latitude: 34.0605,
    longitude: -118.2682,
    foundationYear: 1994,
    type: "Business",
    mission: "Support Korean business owners and entrepreneurs",
    services: ["Networking", "Business resources"],
    contactInfo: "info@kba.org",
    registrantId: 15,
    connections: [
      { targetId: 5, targetType: "migrant", strength: 2, type: "business" },
      {
        targetId: 11,
        targetType: "organization",
        strength: 4,
        type: "collaboration",
      },
    ],
  },
  {
    id: 16,
    name: "Korean Community Health Center",
    latitude: 34.0723,
    longitude: -118.2575,
    foundationYear: 2008,
    type: "Health",
    mission: "Provide health services to the Korean community",
    services: ["Health screenings", "Wellness programs"],
    contactInfo: "info@kchc.org",
    registrantId: 16,
    connections: [
      { targetId: 10, targetType: "migrant", strength: 5, type: "health" },
      {
        targetId: 12,
        targetType: "organization",
        strength: 3,
        type: "collaboration",
      },
    ],
  },
  {
    id: 17,
    name: "Korean American Coalition for Education",
    latitude: 34.0637,
    longitude: -118.2934,
    foundationYear: 2013,
    type: "Educational",
    mission: "Enhance educational opportunities for Korean Americans",
    services: ["Scholarships", "Tutoring programs"],
    contactInfo: "info@kace.org",
    registrantId: 17,
    connections: [
      { targetId: 9, targetType: "migrant", strength: 3, type: "educational" },
      {
        targetId: 6,
        targetType: "organization",
        strength: 4,
        type: "collaboration",
      },
    ],
  },
  {
    id: 18,
    name: "Korean Environmental Association",
    latitude: 34.069,
    longitude: -118.2615,
    foundationYear: 2011,
    type: "Environmental",
    mission: "Promote environmental awareness in the Korean community",
    services: ["Workshops", "Community cleanups"],
    contactInfo: "info@kea.org",
    registrantId: 18,
    connections: [
      {
        targetId: 7,
        targetType: "migrant",
        strength: 2,
        type: "environmental",
      },
      {
        targetId: 14,
        targetType: "organization",
        strength: 5,
        type: "collaboration",
      },
    ],
  },
  {
    id: 19,
    name: "Korean Student Association",
    latitude: 34.075,
    longitude: -118.2478,
    foundationYear: 1997,
    type: "Youth",
    mission: "Support Korean students in higher education",
    services: ["Student mentorship", "Cultural events"],
    contactInfo: "info@ksa.org",
    registrantId: 19,
    connections: [
      { targetId: 8, targetType: "migrant", strength: 4, type: "youth" },
      {
        targetId: 16,
        targetType: "organization",
        strength: 5,
        type: "collaboration",
      },
    ],
  },
  {
    id: 20,
    name: "Korean Language and Culture Center",
    latitude: 34.0697,
    longitude: -118.2774,
    foundationYear: 1999,
    type: "Cultural",
    mission: "Enhance understanding of Korean language and culture",
    services: ["Language classes", "Cultural workshops"],
    contactInfo: "info@klcc.org",
    registrantId: 20,
    connections: [
      { targetId: 3, targetType: "migrant", strength: 3, type: "educational" },
      {
        targetId: 13,
        targetType: "organization",
        strength: 4,
        type: "collaboration",
      },
    ],
  },
  {
    id: 21,
    name: "Far East Korean Cultural Association",
    latitude: 43.1198,
    longitude: 131.8869,
    foundationYear: 1993,
    type: "Cultural",
    mission: "Promote Korean culture in the Russian Far East",
    services: ["Cultural events", "Language support"],
    contactInfo: "contact@fekca.org",
    registrantId: 1,
    connections: [
      { targetId: 5, targetType: "migrant", strength: 3, type: "cultural" },
      {
        targetId: 10,
        targetType: "organization",
        strength: 4,
        type: "cultural",
      },
    ],
  },
  {
    id: 22,
    name: "Sydney Korean Business Association",
    latitude: -33.8688,
    longitude: 151.2093,
    foundationYear: 2001,
    type: "Business",
    mission: "Support Korean business owners in Sydney",
    services: ["Networking", "Business support"],
    contactInfo: "info@skba.org",
    registrantId: 2,
    connections: [
      {
        targetId: 17,
        targetType: "organization",
        strength: 5,
        type: "business",
      },
      {
        targetId: 13,
        targetType: "organization",
        strength: 4,
        type: "networking",
      },
    ],
  },
  {
    id: 23,
    name: "Tokyo Korean Cultural Exchange Center",
    latitude: 35.6762,
    longitude: 139.6503,
    foundationYear: 1985,
    type: "Cultural",
    mission: "Promote Korean-Japanese cultural exchanges",
    services: ["Cultural festivals", "Language exchange"],
    contactInfo: "contact@tkcec.org",
    registrantId: 3,
    connections: [
      { targetId: 4, targetType: "migrant", strength: 4, type: "cultural" },
      {
        targetId: 19,
        targetType: "organization",
        strength: 3,
        type: "collaboration",
      },
    ],
  },
  {
    id: 24,
    name: "Vladivostok Korean Community Center",
    latitude: 43.1155,
    longitude: 131.8855,
    foundationYear: 1990,
    type: "Community",
    mission: "Support the Korean community in Vladivostok",
    services: ["Legal aid", "Community outreach"],
    contactInfo: "info@vkcc.org",
    registrantId: 4,
    connections: [
      {
        targetId: 16,
        targetType: "organization",
        strength: 5,
        type: "legal",
      },
      {
        targetId: 6,
        targetType: "organization",
        strength: 4,
        type: "community",
      },
    ],
  },
  {
    id: 25,
    name: "Melbourne Korean Business Hub",
    latitude: -37.8136,
    longitude: 144.9631,
    foundationYear: 2008,
    type: "Business",
    mission: "Promote Korean business interests in Melbourne",
    services: ["Business workshops", "Networking"],
    contactInfo: "info@mkbh.org",
    registrantId: 5,
    connections: [
      {
        targetId: 8,
        targetType: "organization",
        strength: 4,
        type: "business",
      },
      {
        targetId: 12,
        targetType: "organization",
        strength: 3,
        type: "collaboration",
      },
    ],
  },
  {
    id: 26,
    name: "Korean Heritage Association of New York",
    latitude: 40.7128,
    longitude: -74.006,
    foundationYear: 1995,
    type: "Cultural",
    mission: "Preserve and promote Korean heritage in New York",
    services: ["Cultural events", "Workshops"],
    contactInfo: "info@khan.org",
    registrantId: 6,
    connections: [
      {
        targetId: 11,
        targetType: "organization",
        strength: 5,
        type: "cultural",
      },
      {
        targetId: 7,
        targetType: "migrant",
        strength: 4,
        type: "community",
      },
    ],
  },
  {
    id: 27,
    name: "Korean Community Services of Southern California",
    latitude: 34.0522,
    longitude: -118.2437,
    foundationYear: 1980,
    type: "Community",
    mission: "Serve the Korean community in Southern California",
    services: ["Legal assistance", "Social services"],
    contactInfo: "contact@kcsc.org",
    registrantId: 7,
    connections: [
      {
        targetId: 3,
        targetType: "organization",
        strength: 4,
        type: "social",
      },
      {
        targetId: 14,
        targetType: "migrant",
        strength: 3,
        type: "community",
      },
    ],
  },
  {
    id: 28,
    name: "Korean American Coalition",
    latitude: 34.0522,
    longitude: -118.2437,
    foundationYear: 1999,
    type: "Advocacy",
    mission: "Advocate for Korean Americans' rights",
    services: ["Advocacy", "Education"],
    contactInfo: "info@kac.org",
    registrantId: 8,
    connections: [
      {
        targetId: 18,
        targetType: "organization",
        strength: 5,
        type: "advocacy",
      },
      {
        targetId: 15,
        targetType: "organization",
        strength: 4,
        type: "education",
      },
    ],
  },
  {
    id: 29,
    name: "Korean Cultural Center in Los Angeles",
    latitude: 34.0635,
    longitude: -118.2488,
    foundationYear: 2001,
    type: "Cultural",
    mission: "Promote Korean culture and arts in Los Angeles",
    services: ["Cultural programs", "Exhibitions"],
    contactInfo: "info@kccla.org",
    registrantId: 9,
    connections: [
      {
        targetId: 2,
        targetType: "organization",
        strength: 4,
        type: "cultural",
      },
      {
        targetId: 20,
        targetType: "organization",
        strength: 3,
        type: "collaboration",
      },
    ],
  },
  {
    id: 30,
    name: "Seoul Global Center",
    latitude: 37.5665,
    longitude: 126.978,
    foundationYear: 2004,
    type: "Government",
    mission: "Support international residents in Seoul",
    services: ["Consultation", "Workshops"],
    contactInfo: "info@sgc.go.kr",
    registrantId: 10,
    connections: [
      {
        targetId: 9,
        targetType: "organization",
        strength: 4,
        type: "support",
      },
      {
        targetId: 1,
        targetType: "migrant",
        strength: 3,
        type: "community",
      },
    ],
  },
  {
    id: 31,
    name: "Korean Society of Washington, D.C.",
    latitude: 38.9072,
    longitude: -77.0369,
    foundationYear: 1986,
    type: "Cultural",
    mission: "Promote Korean culture and heritage in D.C.",
    services: ["Cultural programs", "Networking"],
    contactInfo: "contact@kswdc.org",
    registrantId: 11,
    connections: [
      {
        targetId: 1,
        targetType: "organization",
        strength: 5,
        type: "cultural",
      },
      {
        targetId: 14,
        targetType: "migrant",
        strength: 3,
        type: "community",
      },
    ],
  },
  {
    id: 32,
    name: "Korean American Student Association",
    latitude: 39.7392,
    longitude: -104.9903,
    foundationYear: 2010,
    type: "Student",
    mission: "Support Korean students in Colorado",
    services: ["Tutoring", "Networking"],
    contactInfo: "info@kasa.org",
    registrantId: 12,
    connections: [
      {
        targetId: 5,
        targetType: "migrant",
        strength: 3,
        type: "support",
      },
      {
        targetId: 18,
        targetType: "organization",
        strength: 2,
        type: "education",
      },
    ],
  },
  {
    id: 33,
    name: "Korean National Association",
    latitude: 37.5665,
    longitude: 126.978,
    foundationYear: 1921,
    type: "Historical",
    mission: "Support Korean independence and rights",
    services: ["Advocacy", "Networking"],
    contactInfo: "contact@kna.org",
    registrantId: 13,
    connections: [
      {
        targetId: 4,
        targetType: "organization",
        strength: 5,
        type: "advocacy",
      },
      {
        targetId: 20,
        targetType: "migrant",
        strength: 3,
        type: "networking",
      },
    ],
  },
  {
    id: 34,
    name: "Global Korean Network",
    latitude: 34.0522,
    longitude: -118.2437,
    foundationYear: 2015,
    type: "Network",
    mission: "Connect Korean communities worldwide",
    services: ["Networking", "Cultural exchange"],
    contactInfo: "info@gkn.org",
    registrantId: 14,
    connections: [
      {
        targetId: 12,
        targetType: "organization",
        strength: 4,
        type: "networking",
      },
      {
        targetId: 19,
        targetType: "migrant",
        strength: 3,
        type: "exchange",
      },
    ],
  },
  {
    id: 35,
    name: "Korean Women’s Association",
    latitude: 37.5665,
    longitude: 126.978,
    foundationYear: 1999,
    type: "Advocacy",
    mission: "Support and empower Korean women",
    services: ["Advocacy", "Workshops"],
    contactInfo: "info@kwa.org",
    registrantId: 15,
    connections: [
      {
        targetId: 8,
        targetType: "organization",
        strength: 5,
        type: "advocacy",
      },
      {
        targetId: 16,
        targetType: "organization",
        strength: 3,
        type: "support",
      },
    ],
  },
  {
    id: 36,
    name: "Far East Korean Cultural Association",
    latitude: 43.1198,
    longitude: 131.8869,
    foundationYear: 1993,
    type: "Cultural",
    mission: "Promote Korean culture in the Russian Far East",
    services: ["Cultural events", "Language support"],
    contactInfo: "contact@fekca.org",
    registrantId: 1,
    connections: [
      { targetId: 5, targetType: "migrant", strength: 3, type: "cultural" },
      {
        targetId: 10,
        targetType: "organization",
        strength: 4,
        type: "cultural",
      },
    ],
  },
  {
    id: 37,
    name: "Sydney Korean Business Association",
    latitude: -33.8688,
    longitude: 151.2093,
    foundationYear: 2001,
    type: "Business",
    mission: "Support Korean business owners in Sydney",
    services: ["Networking", "Business support"],
    contactInfo: "info@skba.org",
    registrantId: 2,
    connections: [
      {
        targetId: 17,
        targetType: "organization",
        strength: 5,
        type: "business",
      },
      {
        targetId: 13,
        targetType: "organization",
        strength: 4,
        type: "networking",
      },
    ],
  },
  {
    id: 38,
    name: "Tokyo Korean Cultural Exchange Center",
    latitude: 35.6762,
    longitude: 139.6503,
    foundationYear: 1985,
    type: "Cultural",
    mission: "Promote Korean-Japanese cultural exchanges",
    services: ["Cultural festivals", "Language exchange"],
    contactInfo: "contact@tkcec.org",
    registrantId: 3,
    connections: [
      { targetId: 4, targetType: "migrant", strength: 4, type: "cultural" },
      {
        targetId: 19,
        targetType: "organization",
        strength: 3,
        type: "collaboration",
      },
    ],
  },
  {
    id: 39,
    name: "Vladivostok Korean Community Center",
    latitude: 43.1155,
    longitude: 131.8855,
    foundationYear: 1990,
    type: "Community",
    mission: "Support the Korean community in Vladivostok",
    services: ["Legal aid", "Community outreach"],
    contactInfo: "info@vkcc.org",
    registrantId: 4,
    connections: [
      {
        targetId: 16,
        targetType: "organization",
        strength: 5,
        type: "legal",
      },
      {
        targetId: 6,
        targetType: "organization",
        strength: 4,
        type: "community",
      },
    ],
  },
  {
    id: 40,
    name: "Melbourne Korean Business Hub",
    latitude: -37.8136,
    longitude: 144.9631,
    foundationYear: 2008,
    type: "Business",
    mission: "Promote Korean business interests in Melbourne",
    services: ["Business workshops", "Networking"],
    contactInfo: "info@mkbh.org",
    registrantId: 5,
    connections: [
      {
        targetId: 8,
        targetType: "organization",
        strength: 4,
        type: "business",
      },
      {
        targetId: 12,
        targetType: "organization",
        strength: 3,
        type: "collaboration",
      },
    ],
  },
  {
    id: 41,
    name: "Korean Heritage Association of New York",
    latitude: 40.7128,
    longitude: -74.006,
    foundationYear: 1995,
    type: "Cultural",
    mission: "Preserve and promote Korean heritage in New York",
    services: ["Cultural events", "Workshops"],
    contactInfo: "info@khan.org",
    registrantId: 6,
    connections: [
      {
        targetId: 11,
        targetType: "organization",
        strength: 5,
        type: "cultural",
      },
      {
        targetId: 7,
        targetType: "migrant",
        strength: 4,
        type: "community",
      },
    ],
  },
  {
    id: 42,
    name: "Korean Community Services of Southern California",
    latitude: 34.0522,
    longitude: -118.2437,
    foundationYear: 1980,
    type: "Community",
    mission: "Serve the Korean community in Southern California",
    services: ["Legal assistance", "Social services"],
    contactInfo: "contact@kcsc.org",
    registrantId: 7,
    connections: [
      {
        targetId: 3,
        targetType: "organization",
        strength: 4,
        type: "social",
      },
      {
        targetId: 14,
        targetType: "migrant",
        strength: 3,
        type: "community",
      },
    ],
  },
  {
    id: 43,
    name: "Korean American Coalition",
    latitude: 34.0522,
    longitude: -118.2437,
    foundationYear: 1999,
    type: "Advocacy",
    mission: "Advocate for Korean Americans' rights",
    services: ["Advocacy", "Education"],
    contactInfo: "info@kac.org",
    registrantId: 8,
    connections: [
      {
        targetId: 18,
        targetType: "organization",
        strength: 5,
        type: "advocacy",
      },
      {
        targetId: 15,
        targetType: "organization",
        strength: 4,
        type: "education",
      },
    ],
  },
  {
    id: 44,
    name: "Korean Cultural Center in Los Angeles",
    latitude: 34.0635,
    longitude: -118.2488,
    foundationYear: 2001,
    type: "Cultural",
    mission: "Promote Korean culture and arts in Los Angeles",
    services: ["Cultural programs", "Exhibitions"],
    contactInfo: "info@kccla.org",
    registrantId: 9,
    connections: [
      {
        targetId: 2,
        targetType: "organization",
        strength: 4,
        type: "cultural",
      },
      {
        targetId: 20,
        targetType: "organization",
        strength: 3,
        type: "collaboration",
      },
    ],
  },
  {
    id: 45,
    name: "Seoul Global Center",
    latitude: 37.5665,
    longitude: 126.978,
    foundationYear: 2004,
    type: "Government",
    mission: "Support international residents in Seoul",
    services: ["Consultation", "Workshops"],
    contactInfo: "info@sgc.go.kr",
    registrantId: 10,
    connections: [
      {
        targetId: 9,
        targetType: "organization",
        strength: 4,
        type: "support",
      },
      {
        targetId: 1,
        targetType: "migrant",
        strength: 3,
        type: "community",
      },
    ],
  },
];
