// members.ts
export const members = [
  {
    id: 1,
    name: "Haha Hoho",
    email: "hahahoho@naver.com",
    password: "1234",
  },
  {
    id: 2,
    name: "John Doe",
    email: "johndoe@example.com",
    password: "securepassword",
  },
  {
    id: 3,
    name: "Sakura Yamamoto",
    email: "sakura.yamamoto@example.jp",
    password: "sakupass",
  },
  {
    id: 4,
    name: "Carlos García",
    email: "carlos.garcia@example.es",
    password: "carlospass",
  },
  {
    id: 5,
    name: "Amir Khan",
    email: "amir.khan@example.in",
    password: "amirpass",
  },
  {
    id: 6,
    name: "Nina Petrova",
    email: "nina.petrova@example.ru",
    password: "ninapass",
  },
  {
    id: 7,
    name: "Ming Wei",
    email: "ming.wei@example.cn",
    password: "mingpass",
  },
  {
    id: 8,
    name: "Fatima Al-Sayed",
    email: "fatima.sayed@example.ae",
    password: "fatimapass",
  },
  {
    id: 9,
    name: "Liam O'Connor",
    email: "liam.oconnor@example.ie",
    password: "liampass",
  },
  {
    id: 10,
    name: "Chloe Dupont",
    email: "chloe.dupont@example.fr",
    password: "chloepass",
  },
  {
    id: 11,
    name: "Hana Kim",
    email: "hana.kim@example.kr",
    password: "hanapass",
  },
  {
    id: 12,
    name: "Jakub Nowak",
    email: "jakub.nowak@example.pl",
    password: "jakubpass",
  },
  {
    id: 13,
    name: "Sophia Rossi",
    email: "sophia.rossi@example.it",
    password: "sophiapass",
  },
  {
    id: 14,
    name: "Emily Johnson",
    email: "emily.johnson@example.ca",
    password: "emilypass",
  },
  {
    id: 15,
    name: "Ahmed Ben Ali",
    email: "ahmed.benali@example.dz",
    password: "ahmedpass",
  },
  {
    id: 16,
    name: "Yuki Tanaka",
    email: "yuki.tanaka@example.jp",
    password: "yukipass",
  },
  {
    id: 17,
    name: "Lucas Müller",
    email: "lucas.muller@example.de",
    password: "lucaspass",
  },
  {
    id: 18,
    name: "Olivia Svensson",
    email: "olivia.svensson@example.se",
    password: "oliviapass",
  },
  {
    id: 19,
    name: "Isabella Santos",
    email: "isabella.santos@example.br",
    password: "isabellapass",
  },
  {
    id: 20,
    name: "Amina Diallo",
    email: "amina.diallo@example.sn",
    password: "aminapass",
  },
];
