import { Migrant, Organization } from "./types";

export const mockMigrants: Migrant[] = [
  {
    id: 1,
    name: "Kim Minjun",
    nationality: "Korean",
    ethnicity: "Korean",
    latitude: 37.5665,
    longitude: 126.978,
    migrationYear: 2015,
    age: 35,
    occupation: "Software Engineer",
    education: "Bachelor's in Computer Science",
    languagesSpoken: ["Korean", "English"],
    connections: [
      { targetId: 2, targetType: "migrant", strength: 4, type: "friend" },
      { targetId: 3, targetType: "migrant", strength: 2, type: "friend" },
      { targetId: 4, targetType: "migrant", strength: 2, type: "friend" },

      {
        targetId: 1,
        targetType: "organization",
        strength: 3,
        type: "professional",
      },
    ],
  },
  {
    id: 2,
    name: "Liu Wei",
    nationality: "Chinese",
    ethnicity: "Han Chinese",
    latitude: 31.2304,
    longitude: 121.4737,
    migrationYear: 2010,
    age: 40,
    occupation: "Business Analyst",
    education: "Master's in Finance",
    languagesSpoken: ["Mandarin", "English"],
    connections: [
      { targetId: 3, targetType: "migrant", strength: 2, type: "colleague" },
      {
        targetId: 1,
        targetType: "organization",
        strength: 3,
        type: "business",
      },
    ],
  },
  {
    id: 3,
    name: "John Smith",
    nationality: "American",
    ethnicity: "Caucasian",
    latitude: 40.7128,
    longitude: -74.006,
    migrationYear: 2008,
    age: 45,
    occupation: "Marketing Manager",
    education: "Bachelor's in Marketing",
    languagesSpoken: ["English", "Spanish"],
    connections: [
      { targetId: 4, targetType: "migrant", strength: 5, type: "friend" },
      {
        targetId: 2,
        targetType: "organization",
        strength: 2,
        type: "business",
      },
    ],
  },
  {
    id: 4,
    name: "Sophie Dupont",
    nationality: "French",
    ethnicity: "European",
    latitude: 48.8566,
    longitude: 2.3522,
    migrationYear: 2017,
    age: 29,
    occupation: "Fashion Designer",
    education: "Bachelor's in Fashion Design",
    languagesSpoken: ["French", "English"],
    connections: [
      { targetId: 5, targetType: "migrant", strength: 3, type: "colleague" },
      {
        targetId: 3,
        targetType: "organization",
        strength: 4,
        type: "cultural",
      },
    ],
  },
  {
    id: 5,
    name: "Ali Hassan",
    nationality: "Egyptian",
    ethnicity: "Arab",
    latitude: 30.0444,
    longitude: 31.2357,
    migrationYear: 2012,
    age: 32,
    occupation: "Civil Engineer",
    education: "Master's in Civil Engineering",
    languagesSpoken: ["Arabic", "English"],
    connections: [
      { targetId: 2, targetType: "migrant", strength: 4, type: "friend" },
      { targetId: 3, targetType: "migrant", strength: 2, type: "friend" },
      { targetId: 4, targetType: "migrant", strength: 2, type: "friend" },
      { targetId: 6, targetType: "migrant", strength: 4, type: "friend" },
      {
        targetId: 4,
        targetType: "organization",
        strength: 3,
        type: "professional",
      },
    ],
  },
  {
    id: 6,
    name: "Maria Fernandez",
    nationality: "Mexican",
    ethnicity: "Latino",
    latitude: 19.4326,
    longitude: -99.1332,
    migrationYear: 2018,
    age: 30,
    occupation: "Teacher",
    education: "Bachelor's in Education",
    languagesSpoken: ["Spanish", "English"],
    connections: [
      {
        targetId: 1,
        targetType: "organization",
        strength: 4,
        type: "professional",
      },
      { targetId: 7, targetType: "migrant", strength: 5, type: "friend" },
    ],
  },
  {
    id: 7,
    name: "Ahmed Al-Sayed",
    nationality: "Jordanian",
    ethnicity: "Arab",
    latitude: 31.9632,
    longitude: 35.9308,
    migrationYear: 2019,
    age: 29,
    occupation: "Doctor",
    education: "Bachelor's in Medicine",
    languagesSpoken: ["Arabic", "English"],
    connections: [
      {
        targetId: 2,
        targetType: "organization",
        strength: 3,
        type: "business",
      },
      { targetId: 6, targetType: "migrant", strength: 5, type: "friend" },
    ],
  },
  {
    id: 8,
    name: "Olga Ivanova",
    nationality: "Russian",
    ethnicity: "Slavic",
    latitude: 55.7558,
    longitude: 37.6173,
    migrationYear: 2012,
    age: 36,
    occupation: "Engineer",
    education: "Master's in Mechanical Engineering",
    languagesSpoken: ["Russian", "English"],
    connections: [
      { targetId: 2, targetType: "migrant", strength: 4, type: "friend" },
      { targetId: 3, targetType: "migrant", strength: 2, type: "friend" },
      { targetId: 4, targetType: "migrant", strength: 3, type: "colleague" },
      {
        targetId: 1,
        targetType: "organization",
        strength: 2,
        type: "cultural",
      },
    ],
  },
  {
    id: 9,
    name: "Linh Nguyen",
    nationality: "Vietnamese",
    ethnicity: "Vietnamese",
    latitude: 21.0285,
    longitude: 105.8542,
    migrationYear: 2016,
    age: 28,
    occupation: "Accountant",
    education: "Bachelor's in Accounting",
    languagesSpoken: ["Vietnamese", "English"],
    connections: [
      {
        targetId: 4,
        targetType: "organization",
        strength: 3,
        type: "business",
      },
      { targetId: 9, targetType: "migrant", strength: 4, type: "friend" },
    ],
  },
  {
    id: 10,
    name: "Rajesh Kumar",
    nationality: "Indian",
    ethnicity: "South Asian",
    latitude: 28.6139,
    longitude: 77.209,
    migrationYear: 2014,
    age: 34,
    occupation: "Data Scientist",
    education: "Master's in Data Science",
    languagesSpoken: ["Hindi", "English"],
    connections: [
      {
        targetId: 5,
        targetType: "organization",
        strength: 4,
        type: "professional",
      },
      { targetId: 2, targetType: "migrant", strength: 4, type: "friend" },
      { targetId: 3, targetType: "migrant", strength: 2, type: "friend" },
      { targetId: 4, targetType: "migrant", strength: 2, type: "friend" },
      { targetId: 10, targetType: "migrant", strength: 3, type: "colleague" },
    ],
  },
  {
    id: 11,
    name: "Aisha Mbeki",
    nationality: "South African",
    ethnicity: "African",
    latitude: -26.2041,
    longitude: 28.0473,
    migrationYear: 2011,
    age: 39,
    occupation: "Social Worker",
    education: "Bachelor's in Social Work",
    languagesSpoken: ["Zulu", "English"],
    connections: [
      {
        targetId: 5,
        targetType: "organization",
        strength: 5,
        type: "community",
      },
      { targetId: 6, targetType: "migrant", strength: 3, type: "friend" },
    ],
  },
  {
    id: 12,
    name: "Ivan Petrov",
    nationality: "Bulgarian",
    ethnicity: "Eastern European",
    latitude: 42.6977,
    longitude: 23.3219,
    migrationYear: 2013,
    age: 33,
    occupation: "IT Specialist",
    education: "Bachelor's in Information Technology",
    languagesSpoken: ["Bulgarian", "English"],
    connections: [
      { targetId: 7, targetType: "migrant", strength: 3, type: "friend" },
      {
        targetId: 5,
        targetType: "organization",
        strength: 4,
        type: "cultural",
      },
    ],
  },
  {
    id: 13,
    name: "Sara Rossi",
    nationality: "Italian",
    ethnicity: "European",
    latitude: 41.9028,
    longitude: 12.4964,
    migrationYear: 2020,
    age: 25,
    occupation: "Graphic Designer",
    education: "Bachelor's in Graphic Design",
    languagesSpoken: ["Italian", "English"],
    connections: [
      {
        targetId: 8,
        targetType: "organization",
        strength: 4,
        type: "cultural",
      },
      { targetId: 3, targetType: "migrant", strength: 3, type: "colleague" },
    ],
  },
  {
    id: 14,
    name: "Mika Tanaka",
    nationality: "Japanese",
    ethnicity: "Japanese",
    latitude: 35.6895,
    longitude: 139.6917,
    migrationYear: 2021,
    age: 27,
    occupation: "Content Creator",
    education: "Bachelor's in Media Studies",
    languagesSpoken: ["Japanese", "English"],
    connections: [
      { targetId: 2, targetType: "migrant", strength: 4, type: "friend" },
      { targetId: 3, targetType: "migrant", strength: 2, type: "friend" },
      { targetId: 4, targetType: "migrant", strength: 2, type: "friend" },
      { targetId: 9, targetType: "migrant", strength: 3, type: "colleague" },
      {
        targetId: 1,
        targetType: "organization",
        strength: 4,
        type: "professional",
      },
    ],
  },
  {
    id: 15,
    name: "Carlos Garcia",
    nationality: "Spanish",
    ethnicity: "European",
    latitude: 40.4168,
    longitude: -3.7038,
    migrationYear: 2010,
    age: 42,
    occupation: "Architect",
    education: "Master's in Architecture",
    languagesSpoken: ["Spanish", "English"],
    connections: [
      { targetId: 6, targetType: "migrant", strength: 3, type: "colleague" },
      {
        targetId: 5,
        targetType: "organization",
        strength: 5,
        type: "business",
      },
    ],
  },
  {
    id: 16,
    name: "Dmitry Volkov",
    nationality: "Russian",
    ethnicity: "Slavic",
    latitude: 59.9343,
    longitude: 30.3351,
    migrationYear: 2014,
    age: 37,
    occupation: "Cybersecurity Analyst",
    education: "Master's in Computer Science",
    languagesSpoken: ["Russian", "English"],
    connections: [
      { targetId: 2, targetType: "migrant", strength: 4, type: "colleague" },
      { targetId: 5, targetType: "migrant", strength: 3, type: "friend" },
      {
        targetId: 2,
        targetType: "organization",
        strength: 5,
        type: "professional",
      },
    ],
  },
  {
    id: 17,
    name: "Irina Petrova",
    nationality: "Russian",
    ethnicity: "Slavic",
    latitude: 55.7558,
    longitude: 37.6173,
    migrationYear: 2016,
    age: 34,
    occupation: "Journalist",
    education: "Bachelor's in Journalism",
    languagesSpoken: ["Russian", "English", "French"],
    connections: [
      { targetId: 9, targetType: "migrant", strength: 5, type: "friend" },
      {
        targetId: 8,
        targetType: "organization",
        strength: 4,
        type: "media",
      },
    ],
  },
  {
    id: 18,
    name: "Natalya Ivanova",
    nationality: "Russian",
    ethnicity: "Slavic",
    latitude: 56.3269,
    longitude: 44.0077,
    migrationYear: 2012,
    age: 38,
    occupation: "Project Manager",
    education: "Master's in Business Administration",
    languagesSpoken: ["Russian", "English"],
    connections: [
      { targetId: 10, targetType: "migrant", strength: 3, type: "colleague" },
      { targetId: 11, targetType: "migrant", strength: 2, type: "friend" },
      {
        targetId: 7,
        targetType: "organization",
        strength: 5,
        type: "business",
      },
    ],
  },
  {
    id: 19,
    name: "Sergei Morozov",
    nationality: "Russian",
    ethnicity: "Slavic",
    latitude: 54.9893,
    longitude: 73.3686,
    migrationYear: 2010,
    age: 40,
    occupation: "Software Developer",
    education: "Bachelor's in Computer Science",
    languagesSpoken: ["Russian", "English"],
    connections: [
      { targetId: 2, targetType: "migrant", strength: 4, type: "colleague" },
      {
        targetId: 5,
        targetType: "organization",
        strength: 5,
        type: "professional",
      },
    ],
  },
  {
    id: 20,
    name: "Anastasia Fedorova",
    nationality: "Russian",
    ethnicity: "Slavic",
    latitude: 51.5074,
    longitude: -0.1278,
    migrationYear: 2018,
    age: 29,
    occupation: "Graphic Designer",
    education: "Bachelor's in Fine Arts",
    languagesSpoken: ["Russian", "English"],
    connections: [
      { targetId: 12, targetType: "migrant", strength: 4, type: "friend" },
      {
        targetId: 1,
        targetType: "organization",
        strength: 4,
        type: "cultural",
      },
    ],
  },
  {
    id: 21,
    name: "Oleg Kuznetsov",
    nationality: "Russian",
    ethnicity: "Slavic",
    latitude: 45.0448,
    longitude: 38.976,
    migrationYear: 2013,
    age: 35,
    occupation: "Mechanical Engineer",
    education: "Master's in Mechanical Engineering",
    languagesSpoken: ["Russian", "English"],
    connections: [
      { targetId: 8, targetType: "migrant", strength: 3, type: "colleague" },
      {
        targetId: 4,
        targetType: "organization",
        strength: 4,
        type: "technical",
      },
    ],
  },
  {
    id: 22,
    name: "Svetlana Popova",
    nationality: "Russian",
    ethnicity: "Slavic",
    latitude: 53.2001,
    longitude: 50.15,
    migrationYear: 2017,
    age: 32,
    occupation: "Marketing Specialist",
    education: "Master's in Marketing",
    languagesSpoken: ["Russian", "English", "German"],
    connections: [
      { targetId: 9, targetType: "migrant", strength: 5, type: "friend" },
      {
        targetId: 1,
        targetType: "organization",
        strength: 3,
        type: "business",
      },
    ],
  },
  {
    id: 23,
    name: "Alexei Romanov",
    nationality: "Russian",
    ethnicity: "Slavic",
    latitude: 55.0415,
    longitude: 82.9346,
    migrationYear: 2015,
    age: 33,
    occupation: "Research Scientist",
    education: "PhD in Physics",
    languagesSpoken: ["Russian", "English"],
    connections: [
      { targetId: 3, targetType: "migrant", strength: 4, type: "colleague" },
      {
        targetId: 7,
        targetType: "organization",
        strength: 5,
        type: "academic",
      },
    ],
  },
  {
    id: 24,
    name: "Ekaterina Smirnova",
    nationality: "Russian",
    ethnicity: "Slavic",
    latitude: 55.7558,
    longitude: 37.6173,
    migrationYear: 2016,
    age: 28,
    occupation: "Lawyer",
    education: "Master's in Law",
    languagesSpoken: ["Russian", "English", "French"],
    connections: [
      { targetId: 12, targetType: "migrant", strength: 3, type: "friend" },
      {
        targetId: 10,
        targetType: "organization",
        strength: 4,
        type: "legal",
      },
    ],
  },
  {
    id: 25,
    name: "Natalia Sokolova",
    nationality: "Russian",
    ethnicity: "Slavic",
    latitude: 59.9343,
    longitude: 30.3351,
    migrationYear: 2014,
    age: 33,
    occupation: "Environmental Engineer",
    education: "Master's in Environmental Engineering",
    languagesSpoken: ["Russian", "English"],
    connections: [
      { targetId: 21, targetType: "migrant", strength: 4, type: "colleague" },
      { targetId: 22, targetType: "migrant", strength: 3, type: "friend" },
      { targetId: 20, targetType: "migrant", strength: 2, type: "colleague" },
      {
        targetId: 24,
        targetType: "migrant",
        strength: 4,
        type: "professional",
      },
      { targetId: 19, targetType: "migrant", strength: 5, type: "friend" },
      // 추가된 5개의 엣지
      {
        targetId: 16,
        targetType: "migrant",
        strength: 4,
        type: "professional",
      },
      { targetId: 17, targetType: "migrant", strength: 3, type: "friend" },
      { targetId: 23, targetType: "migrant", strength: 4, type: "business" },
      { targetId: 18, targetType: "migrant", strength: 2, type: "colleague" },
      {
        targetId: 25,
        targetType: "organization",
        strength: 5,
        type: "community",
      },
    ],
  },
];

export const mockOrganizations: Organization[] = [
  {
    id: 1,
    name: "Korean Cultural Center - LA",
    latitude: 34.0622,
    longitude: -118.3026,
    foundationYear: 1980,
    type: "Cultural",
    mission: "Promote Korean culture and support Korean immigrants",
    services: ["Language classes", "Cultural events", "Immigration support"],
    contactInfo: "info@kccla.org",
    connections: [
      { targetId: 1, targetType: "migrant", strength: 3, type: "cultural" },
      {
        targetId: 2,
        targetType: "organization",
        strength: 4,
        type: "professional",
      },
    ],
  },
  {
    id: 2,
    name: "Asian Business Association",
    latitude: 34.0522,
    longitude: -118.2437,
    foundationYear: 1995,
    type: "Business",
    mission: "Support Asian business owners in LA",
    services: ["Business workshops", "Networking events"],
    contactInfo: "contact@abala.org",
    connections: [
      { targetId: 2, targetType: "migrant", strength: 2, type: "business" },
      {
        targetId: 1,
        targetType: "organization",
        strength: 4,
        type: "networking",
      },
    ],
  },
  {
    id: 3,
    name: "New York Immigrant Coalition",
    latitude: 40.7128,
    longitude: -74.006,
    foundationYear: 1990,
    type: "Non-Profit",
    mission: "Advocate for immigrant rights",
    services: ["Legal support", "Advocacy", "Community outreach"],
    contactInfo: "info@nyic.org",
    connections: [
      { targetId: 3, targetType: "migrant", strength: 4, type: "legal" },
      {
        targetId: 4,
        targetType: "organization",
        strength: 2,
        type: "advocacy",
      },
    ],
  },
  {
    id: 4,
    name: "European Immigrant Support Center",
    latitude: 48.8566,
    longitude: 2.3522,
    foundationYear: 2005,
    type: "Cultural",
    mission: "Support European immigrants in France",
    services: ["Cultural events", "Language support"],
    contactInfo: "contact@eisc.org",
    connections: [
      { targetId: 4, targetType: "migrant", strength: 4, type: "cultural" },
      {
        targetId: 5,
        targetType: "organization",
        strength: 3,
        type: "cultural",
      },
    ],
  },
  {
    id: 5,
    name: "African Development Association",
    latitude: 9.0579,
    longitude: 7.4951,
    foundationYear: 2010,
    type: "Non-Profit",
    mission: "Foster development in African immigrant communities",
    services: ["Education", "Health support", "Community building"],
    contactInfo: "contact@ada.org",
    connections: [
      { targetId: 5, targetType: "migrant", strength: 4, type: "community" },
      {
        targetId: 3,
        targetType: "organization",
        strength: 3,
        type: "collaboration",
      },
    ],
  },
  {
    id: 6,
    name: "Middle East Cultural Association",
    latitude: 25.276987,
    longitude: 55.296249,
    foundationYear: 1998,
    type: "Cultural",
    mission: "Promote Middle Eastern culture",
    services: ["Cultural events", "Language classes"],
    contactInfo: "info@meca.org",
    connections: [
      { targetId: 6, targetType: "migrant", strength: 4, type: "cultural" },
      {
        targetId: 3,
        targetType: "organization",
        strength: 3,
        type: "collaboration",
      },
    ],
  },
  {
    id: 7,
    name: "Latin American Business Association",
    latitude: -23.55052,
    longitude: -46.633308,
    foundationYear: 2000,
    type: "Business",
    mission: "Support Latin American businesses",
    services: ["Networking", "Business workshops"],
    contactInfo: "contact@laba.org",
    connections: [
      { targetId: 7, targetType: "migrant", strength: 5, type: "business" },
      {
        targetId: 4,
        targetType: "organization",
        strength: 4,
        type: "networking",
      },
    ],
  },
  {
    id: 8,
    name: "Asian Women’s Resource Center",
    latitude: 34.052235,
    longitude: -118.243683,
    foundationYear: 2005,
    type: "Non-Profit",
    mission: "Empower Asian women",
    services: ["Legal support", "Advocacy"],
    contactInfo: "info@awrc.org",
    connections: [
      { targetId: 8, targetType: "migrant", strength: 4, type: "advocacy" },
      {
        targetId: 7,
        targetType: "organization",
        strength: 2,
        type: "community",
      },
    ],
  },
  {
    id: 9,
    name: "European Cultural Institute",
    latitude: 50.110924,
    longitude: 8.682127,
    foundationYear: 1999,
    type: "Cultural",
    mission: "Promote European cultural exchanges",
    services: ["Cultural festivals", "Language exchange"],
    contactInfo: "contact@eci.org",
    connections: [
      { targetId: 5, targetType: "migrant", strength: 3, type: "cultural" },
      {
        targetId: 6,
        targetType: "organization",
        strength: 2,
        type: "collaboration",
      },
    ],
  },
  {
    id: 10,
    name: "African Diaspora Association",
    latitude: -1.292066,
    longitude: 36.821945,
    foundationYear: 2010,
    type: "Community",
    mission: "Support African diaspora",
    services: ["Job training", "Cultural events"],
    contactInfo: "contact@ada.org",
    connections: [
      { targetId: 10, targetType: "migrant", strength: 5, type: "community" },
      {
        targetId: 5,
        targetType: "organization",
        strength: 3,
        type: "networking",
      },
    ],
  },
  {
    id: 11,
    name: "Russian-Korean Friendship Association",
    latitude: 55.7558,
    longitude: 37.6173,
    foundationYear: 2000,
    type: "Cultural",
    mission: "Promote cultural exchanges between Russia and Korea",
    services: ["Cultural festivals", "Language classes"],
    contactInfo: "contact@rkfa.org",
    connections: [
      { targetId: 11, targetType: "migrant", strength: 4, type: "cultural" },
      {
        targetId: 1,
        targetType: "organization",
        strength: 3,
        type: "collaboration",
      },
      {
        targetId: 7,
        targetType: "organization",
        strength: 3,
        type: "networking",
      },
    ],
  },
  {
    id: 12,
    name: "Vladivostok Immigrant Support Center",
    latitude: 43.1155,
    longitude: 131.8855,
    foundationYear: 1997,
    type: "Non-Profit",
    mission: "Support immigrants settling in Vladivostok",
    services: ["Legal assistance", "Housing support"],
    contactInfo: "info@vladimmigrants.org",
    connections: [
      { targetId: 12, targetType: "migrant", strength: 5, type: "community" },
      {
        targetId: 5,
        targetType: "organization",
        strength: 3,
        type: "collaboration",
      },
      {
        targetId: 6,
        targetType: "organization",
        strength: 2,
        type: "legal support",
      },
    ],
  },
  {
    id: 13,
    name: "Siberian Business Alliance",
    latitude: 55.0084,
    longitude: 82.9357,
    foundationYear: 2010,
    type: "Business",
    mission: "Support small business owners in Siberia",
    services: ["Business workshops", "Networking events"],
    contactInfo: "contact@sba.org",
    connections: [
      { targetId: 13, targetType: "migrant", strength: 4, type: "business" },
      {
        targetId: 2,
        targetType: "organization",
        strength: 4,
        type: "professional",
      },
      {
        targetId: 7,
        targetType: "organization",
        strength: 3,
        type: "networking",
      },
    ],
  },
  {
    id: 14,
    name: "Far East Russian Cultural Center",
    latitude: 53.5288,
    longitude: 127.2042,
    foundationYear: 2005,
    type: "Cultural",
    mission: "Promote Far East Russian culture and traditions",
    services: ["Cultural festivals", "Language exchanges"],
    contactInfo: "info@fercc.org",
    connections: [
      { targetId: 14, targetType: "migrant", strength: 3, type: "cultural" },
      {
        targetId: 4,
        targetType: "organization",
        strength: 2,
        type: "cultural exchange",
      },
      {
        targetId: 9,
        targetType: "organization",
        strength: 4,
        type: "collaboration",
      },
    ],
  },
  {
    id: 15,
    name: "Russian-Korean Cultural Exchange Association",
    latitude: 55.7558,
    longitude: 37.6173,
    foundationYear: 1997,
    type: "Cultural",
    mission: "Facilitate cultural exchanges between Russia and Korea",
    services: ["Cultural events", "Language exchange", "Community support"],
    contactInfo: "contact@rkcea.org",
    connections: [
      { targetId: 7, targetType: "migrant", strength: 3, type: "cultural" },
      {
        targetId: 10,
        targetType: "organization",
        strength: 4,
        type: "networking",
      },
      {
        targetId: 3,
        targetType: "organization",
        strength: 4,
        type: "collaboration",
      },
      {
        targetId: 18,
        targetType: "organization",
        strength: 5,
        type: "cultural",
      },
      { targetId: 12, targetType: "migrant", strength: 4, type: "advocacy" },
      {
        targetId: 9,
        targetType: "organization",
        strength: 3,
        type: "cultural",
      },
      {
        targetId: 6,
        targetType: "organization",
        strength: 3,
        type: "collaboration",
      },
      { targetId: 5, targetType: "migrant", strength: 4, type: "community" },
    ],
  },
  {
    id: 16,
    name: "St. Petersburg Immigrant Legal Aid",
    latitude: 59.9343,
    longitude: 30.3351,
    foundationYear: 2012,
    type: "Non-Profit",
    mission: "Provide legal aid to immigrants in St. Petersburg",
    services: ["Legal support", "Immigration documentation"],
    contactInfo: "contact@spil.org",
    connections: [
      { targetId: 16, targetType: "migrant", strength: 5, type: "legal" },
      {
        targetId: 3,
        targetType: "organization",
        strength: 3,
        type: "legal support",
      },
      {
        targetId: 10,
        targetType: "organization",
        strength: 4,
        type: "community support",
      },
    ],
  },
  {
    id: 17,
    name: "Baikal Development Initiative",
    latitude: 51.8388,
    longitude: 104.8824,
    foundationYear: 2008,
    type: "Non-Profit",
    mission: "Support sustainable development in the Baikal region",
    services: ["Environmental education", "Community support"],
    contactInfo: "contact@bdi.org",
    connections: [
      { targetId: 17, targetType: "migrant", strength: 4, type: "community" },
      {
        targetId: 12,
        targetType: "organization",
        strength: 3,
        type: "sustainability",
      },
      {
        targetId: 11,
        targetType: "organization",
        strength: 4,
        type: "collaboration",
      },
    ],
  },
  {
    id: 18,
    name: "Sakhalin Immigrant Support Foundation",
    latitude: 47.6167,
    longitude: 142.7777,
    foundationYear: 2003,
    type: "Non-Profit",
    mission: "Provide essential services for immigrants in Sakhalin",
    services: ["Housing support", "Job placement"],
    contactInfo: "info@sisf.org",
    connections: [
      { targetId: 18, targetType: "migrant", strength: 5, type: "housing" },
      {
        targetId: 4,
        targetType: "organization",
        strength: 3,
        type: "community",
      },
      {
        targetId: 6,
        targetType: "organization",
        strength: 4,
        type: "support services",
      },
    ],
  },
  {
    id: 19,
    name: "Kazan Business Association",
    latitude: 55.7963,
    longitude: 49.1063,
    foundationYear: 2015,
    type: "Business",
    mission: "Support business growth in Kazan",
    services: ["Networking", "Business workshops"],
    contactInfo: "contact@kba.org",
    connections: [
      { targetId: 19, targetType: "migrant", strength: 4, type: "business" },
      {
        targetId: 15,
        targetType: "organization",
        strength: 5,
        type: "business",
      },
      {
        targetId: 13,
        targetType: "organization",
        strength: 4,
        type: "collaboration",
      },
    ],
  },
  {
    id: 20,
    name: "Siberian Immigrant Welfare Association",
    latitude: 64.6863,
    longitude: 97.7453,
    foundationYear: 2002,
    type: "Non-Profit",
    mission: "Support Korean immigrants in Siberia",
    services: ["Legal aid", "Job training", "Healthcare access"],
    contactInfo: "info@siwa.org",
    connections: [
      {
        targetId: 15,
        targetType: "organization",
        strength: 4,
        type: "welfare",
      },
      { targetId: 14, targetType: "migrant", strength: 5, type: "legal" },
      {
        targetId: 12,
        targetType: "organization",
        strength: 3,
        type: "advocacy",
      },
      { targetId: 18, targetType: "migrant", strength: 4, type: "community" },
      { targetId: 8, targetType: "organization", strength: 3, type: "welfare" },
      { targetId: 5, targetType: "migrant", strength: 4, type: "community" },
      {
        targetId: 3,
        targetType: "organization",
        strength: 4,
        type: "collaboration",
      },
      { targetId: 17, targetType: "organization", strength: 3, type: "legal" },
    ],
  },
];
